#!/bin/bash

# Check if a commit message was provided
if [ -z "$1" ]; then
  echo "Please provide a commit message."
  echo "Usage: ./gitpush.sh \"Your commit message here\""
  exit 1
fi

git add -A && git commit -m "$1" && git push

